### ISSUE TITLE
Create installers

### ISSUE THREAD

**Issue by G07cha** [rhysd/Trendy#5]
For now releases contains ready-to-use applications but another way to distribute apps using installers(more trustful). I can do this but I need to make sure that you need this(that's why I've created issues instead of pull request)

**Comment by rhysd** [comment]
Trendy requires no system permission.  Could you answer what installer improves against current zip distribution?  Actually I don't know what 'more trustful' means.

**Comment by G07cha** [comment]
Installers allows to easy and fast create shortcuts and store application content in proper place(`Applications` for OS X, `Program Files` for Windows).

**Comment by rhysd** [comment]
Thank you for your answer.  That's right.  But users of this app are users of GitHub.  Almost all of them would be engineer.  I think they know the proper `Application` directory to put.  (Of course shortcut link is the same case.)  

If we provide installer,  users must 'install' this app before trying it.  I think trying this app easily before installing to system is more important.

**Comment by G07cha** [comment]
Agreed, closing issue.
